/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ControleVisao;

/**
 *
 * @author gudeck
 */
public class JFRPrincipal extends javax.swing.JFrame {

    private final ControleVisao controladorVisao;

    public JFRPrincipal(ControleVisao controlador) {
        initComponents();
        controladorVisao = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuiCadastroCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuiConsultaCLiente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anarriê");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vision/imagens/Sem título.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 280);

        jMenu1.setText("Cadastro");

        mnuiCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuiCadastroCliente.setText("Cliente");
        mnuiCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiCadastroCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        mnuiConsultaCLiente.setText("Cliente");
        mnuiConsultaCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiConsultaCLienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnuiConsultaCLiente);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Anarrie");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCadastroClienteActionPerformed
        controladorVisao.cadastroCliente();
    }//GEN-LAST:event_mnuiCadastroClienteActionPerformed

    private void mnuiConsultaCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiConsultaCLienteActionPerformed
        controladorVisao.consultaCliente();
    }//GEN-LAST:event_mnuiConsultaCLienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuiCadastroCliente;
    private javax.swing.JMenuItem mnuiConsultaCLiente;
    // End of variables declaration//GEN-END:variables
}
